In [1]:
import sys
import pandas as pd
import numpy as np
import sklearn
import xgboost

In [ ]:
from pathlib import Path

project = Path.cwd()
print("current folder:", project)
print("\nFiles/folders here:")
for item in project.iterdir():
    print(item.name)

project_root = Path.cwd().parent
print("Parent folder:",project_root)

train_source1 = project_root / "data" / "raw" / "train" / "train_source1.tsv"
train_source2 = project_root / "data" / "raw" / "train" / "train_source2.tsv"
train_source3 = project_root / "data" / "raw" / "train" / "train_source3.tsv"

train1 = pd.read_csv(train_source1, sep="\t")
train2 = pd.read_csv(train_source2, sep="\t")
train3 = pd.read_csv(train_source3, sep="\t")

train_gr_truth = project_root / "data" / "raw" / "train" / "train_ground_truth.tsv"
train_gr = pd.read_csv(train_gr_truth, sep="\t")

test_source1 = project_root / "data" / "raw" / "test" / "test_source1.tsv"
test_source2 = project_root / "data" / "raw" / "test" / "test_source2.tsv"
test_source3 = project_root / "data" / "raw" / "test" / "test_source3.tsv"

test1 = pd.read_csv(test_source1, sep="\t")
test2 = pd.read_csv(test_source2, sep="\t")
test3 = pd.read_csv(test_source3, sep="\t")

In [26]:
test1.head(10)

,entity_id,business_name,business_address,country
0,S1-714132312,Zephay Labs Inc,"2621 Cotten Road, Tyler, TX",US
1,S1-106407869,Vision Partners Corp,"IA, Iowa City, 1064 Newton Rd, Unit 11",US
2,S1-156285671,<< Team Ecole,"175 Boulevard du Président Franklin Roosevelt,...",France
3,S1-689823050,Red Perfect Trading,"Mirzapur, Ews 12, Uttar Pradesh, Mirzapursadar...",India
4,S1-921369899,ZNB Club SARL,"Nouvelle-Aquitaine, La Teste-de-Buch, 5 bis Ru...",France
5,S1-481669221,Nandlal Kisan LLP,"D-61 Ifs Apartmentmayur Vihar I, New Delhi, Ea...",India
6,S1-909865979,Cure Seafood,"1325 Brooklyn Walk, Issaquah, WA",US
7,S1-280204013,Om Constructions Pvt Ltd,"Karauli, Rajasthan, Karauli, Pani Ki Tanki Ke ...",India
8,S1-742053041,Roongta Sangh,"Bhubaneswar, Sub Plot No.-L6/29, Mahodadhi Bha...",India
9,S1-913506265,Thermal & Fils SASU,"20 Rue Parmentier, Dunkerque, Hauts-de-France",France

In [28]:
test2.head(10)

,entity_id,business_name,business_address,country
0,S2-192345572,Brahma Infosoft,"COIMATORE COLONY, HUNSUR TQMYSORE DIST., Karna...",India
1,S2-566025912,Marina Ecole France Sarl,"63 R. DE DIEPPE, LILLE, Hauts-de-France",France
2,S2-158121477,SCI Ptit Àmicale,"18 RUE JEN ZAY, Dunkerque, Nord",France
3,S2-89663826,Apex Summit,"67 KENTUCKY ST, SALYERSVILLE, KY",US
4,S2-884102769,Fresh Truist,"8264 FILLY COURT, ROANOKE COUNTY, VA",US
5,S2-910351373,PVT. INDUSTRIES PMB LEASING LIMITED,"SURAT, OFFICE NO. 03038, TRADE HOUSE, NEAR RUS...",India
6,S2-229677112,Clm Agro [Limited],"G-B3/5, T V INDUSTRIAL ESTATE 248/A, S K AHIRE...",India
7,S2-770341988,sci ligue ici parents,"NO. 5 ALLÉE DES HÊTRES, Pornic, Loire-Atlantique",France
8,S2-375151053,A DIAMOND SHORT LLC,"126-B New Line Road, MORRISTOWN, TN",US
9,S2-701289183,Fanni's Dmaigesostcis,"1200 HWY 1187, CROWLEY, TX",US

In [29]:
test3.head(10)

,entity_id,business_name,business_address,country
0,S3-462677478,मॉडर्न फाइनेंस,"No 10 Enkay Square, 448A, Udyog Vihar Phase V,...",India
1,S3-374810425,Shri Sai Infratech Co,"3/115, East Delhi, DL",India
2,S3-198586129,Fractales Amis Groupe S.A.S,"23 Rue Icmre, La Teste-de-buch, Gironde",France
3,S3-10300249,Shri Supreme Consulting Private (Limited),"H.no 910 A 3503, Mumbai, महाराष्ट्र",India
4,S3-604980231,Prime Realty Ventures Public Limited,"G.t. Karnal Road, Industrial Area, New Delhi, ...",India
5,S3-577972146,Perfect Investments Private,"Plot No.99, Flat No.201, Sri Dhama Apts., Road...",India
6,S3-150632472,Pace Mfa PC,"2132 Thomas Run Road, Bel Air, Maryland",US
7,S3-184785497,ஈஸ்டர்ன் கன்சல்டன்சி பிரைவேட் லிமிடெட்,"1410 Sri Mahalakshmi Mandiar 59, Justice Rathi...",India
8,S3-536202929,PU Pvt. Ltd. Services,"TG, Plot No-25, Hyderabad, Qutubullapur, 26, 2...",India
9,S3-560657213,Sun पावर Provision,"143-Alig Flats Rajouri Garden, New Delhi, West...",India

In [41]:
train1.head(10)

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India
5,S3-578159284,LLC Hernandez Colonial Redwood,"2260- Housecreek Trail, Unit 407, Raleigh, Nor...",US
6,S3-121412624,Classic Equity Partners Group,"6885 Catalpa Bluff Ln, PO Box 5799, Dickinson,...",US
7,S3-249416830,Ectolumdrex dba X+ Madison Inc,"S03575 Cty Tk M, Town Of Buffalo, WI",US
8,S3-107644605,Animal Hanisch Hospirlg,"##8 Willow Oak Lane, Fl. 0, Saint Louis, Missouri",US
9,S3-160217003,Gomez Optimal,"343 Hempstead 161, Hope, Arkansas",US

In [42]:
train2.head(10)

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
5       S1-18727616  S2-755677256,S3-187831601,S3-641489370,S3-4762...
6      S1-318373630                          S2-660036492,S3-804600254
7       S1-86989137                          S3-274817120,S3-312496301
8       S1-29845983                          S2-648035184,S3-588502663
9      S1-789009573              S2-383871912,S3-74481402,S3-576451439

In [16]:
train3.head()

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US

In [18]:
train_gr.head()

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [33]:
train1.describe().T

                    count   unique                          top     freq
entity_id         5285603  5285603                 S3-202863386        1
business_name     5285590  4651608                 Primary Care      421
business_address  5109687  4632764  Ground Floor, Bangalore, KA       29
country           5285603        2                           US  3170056

In [37]:
train2.describe().T

,count,unique,top,freq
source1_entity_id,2206821,2206821,S1-965667,1
matched_entity_ids,2083574,2083574,"S2-681193310,S2-743505751,S3-775321672,S3-1129...",1

In [38]:
train3.describe().T

                    count   unique                             top     freq
entity_id         5034616  5034616                    S2-166376419        1
business_name     5034614  4402008                    Primary Care      320
business_address  4865649  4337261  842 38, CALEDONAI TOWNSHIP, WI       18
country           5034616        2                              US  3016817

In [36]:
train1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5285603 entries, 0 to 5285602
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   entity_id         str
 1   business_name     str
 2   business_address  str
 3   country           str
dtypes: str(4)
memory usage: 161.3 MB

In [39]:
train2.info()

<class 'pandas.DataFrame'>
RangeIndex: 2206821 entries, 0 to 2206820
Data columns (total 2 columns):
 #   Column              Dtype
---  ------              -----
 0   source1_entity_id   str
 1   matched_entity_ids  str
dtypes: str(2)
memory usage: 33.7 MB

In [40]:
train3.info()

<class 'pandas.DataFrame'>
RangeIndex: 5034616 entries, 0 to 5034615
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   entity_id         str
 1   business_name     str
 2   business_address  str
 3   country           str
dtypes: str(4)
memory usage: 153.6 MB

In [53]:
train1.shape

(5285603, 4)

In [54]:
train2.shape

(2206821, 2)

In [55]:
train3.shape

(5034616, 4)

In [56]:
train_gr.shape

(2206821, 2)

In [59]:
print("S1:", train1["entity_id"].head(5).tolist())
print("S2:", train2["source1_entity_id"].head(5).tolist())
print("S3:", train3["entity_id"].head(5).tolist())

print("\nPrefixes:")
print("S1:", train1["entity_id"].astype(str).str[:3].unique())
print("S2:", train2["source1_entity_id"].astype(str).str[:3].unique())
print("S3:", train3["entity_id"].astype(str).str[:3].unique())

S1: ['S3-202863386', 'S3-859268022', 'S3-22467283', 'S3-671162755', 'S3-960981775']
S2: ['S1-965667', 'S1-55344266', 'S1-343815751', 'S1-656753428', 'S1-102811957']
S3: ['S2-166376419', 'S2-764573417', 'S2-639257739', 'S2-163963287', 'S2-49942811']

Prefixes:
S1: <StringArray>
['S3-']
Length: 1, dtype: str
S2: <StringArray>
['S1-']
Length: 1, dtype: str
S3: <StringArray>
['S2-']
Length: 1, dtype: str

In [20]:
train2.tail(10)

        source1_entity_id                                 matched_entity_ids
2206811      S1-971492224             S2-380164182,S2-156447569,S3-323293560
2206812      S1-652497556             S2-195142712,S3-387563557,S3-293274778
2206813      S1-587093380                                                NaN
2206814      S1-965343594                          S3-447376424,S3-261884410
2206815        S1-6264355             S2-938325035,S3-734701136,S3-280351985
2206816      S1-824289006                                       S3-141788999
2206817      S1-856943494  S2-950831962,S3-34095479,S3-718748776,S3-44048...
2206818      S1-863031412  S2-518155942,S2-631615245,S3-846786490,S3-1665...
2206819      S1-711234676             S2-908396708,S3-279383973,S3-969901413
2206820      S1-474890318                          S2-271844502,S3-998262924

In [21]:
train_gr.tail(10)

        source1_entity_id                                 matched_entity_ids
2206811      S1-971492224             S2-380164182,S2-156447569,S3-323293560
2206812      S1-652497556             S2-195142712,S3-387563557,S3-293274778
2206813      S1-587093380                                                NaN
2206814      S1-965343594                          S3-447376424,S3-261884410
2206815        S1-6264355             S2-938325035,S3-734701136,S3-280351985
2206816      S1-824289006                                       S3-141788999
2206817      S1-856943494  S2-950831962,S3-34095479,S3-718748776,S3-44048...
2206818      S1-863031412  S2-518155942,S2-631615245,S3-846786490,S3-1665...
2206819      S1-711234676             S2-908396708,S3-279383973,S3-969901413
2206820      S1-474890318                          S2-271844502,S3-998262924

In [18]:
train_gr.query('source1_entity_id == "S1-102811957"')["matched_entity_ids"].value_counts()

matched_entity_ids
S2-478959098,S2-553508714,S2-625774905,S3-728090388,S3-928796641,S3-449308785    1
Name: count, dtype: int64

In [19]:
train2.query('source1_entity_id == "S1-102811957"')["matched_entity_ids"].value_counts()

matched_entity_ids
S2-478959098,S2-553508714,S2-625774905,S3-728090388,S3-928796641,S3-449308785    1
Name: count, dtype: int64

In [32]:
train2["matched_entity_ids"].isna().sum()

np.int64(123247)

In [39]:
ground_truth_map = {}

for _, row in train_gr.iterrows():
    s1_id = row["source1_entity_id"]
    matches = row["matched_entity_ids"]

    if pd.isna(matches) or str(matches).strip() == "":
        ground_truth_map[s1_id] = set()
    else:
        ground_truth_map[s1_id] = set(
            str(matches).split(",")
        )

In [40]:
first_s1 = train_gr.iloc[0]["source1_entity_id"]

print("S1:", first_s1)
print("True matches:", ground_truth_map[first_s1])

S1: S1-965667
True matches: {'S3-860443364', 'S2-681193310', 'S3-11291185', 'S2-743505751', 'S3-775321672'}

In [41]:
def get_target(s1_id, candidate_id):
    return int(candidate_id in ground_truth_map.get(s1_id, set()))

In [42]:
print(get_target(
    "S1-965667",
    "S2-681193310"
))

1

In [43]:
print(get_target(
    "S1-965667",
    "S2-999999999"
))

0

In [44]:
import re
import unicodedata

def normalize_text(text):
    if pd.isna(text):
        return ""
    
    text = str(text)
    
    # Unicode normalization
    text = unicodedata.normalize("NFKC", text)
    
    # Lowercase
    text = text.casefold()
    
    # Replace punctuation with spaces
    text = re.sub(r"[^\w\s]", " ", text)
    
    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()
    
    return text

In [45]:
examples = [
    "ABC Technologies Pvt. Ltd.",
    "ABC TECHNOLOGIES PRIVATE LIMITED",
    "ABC-Tech Pvt Ltd"
]

for x in examples:
    print(x, "→", normalize_text(x))

ABC Technologies Pvt. Ltd. → abc technologies pvt ltd
ABC TECHNOLOGIES PRIVATE LIMITED → abc technologies private limited
ABC-Tech Pvt Ltd → abc tech pvt ltd

In [47]:
train1["name_norm"] = train1["business_name"].apply(normalize_text)

train3["name_norm"] = train3["business_name"].apply(normalize_text)

In [48]:
train1.head()

,entity_id,business_name,business_address,country,name_norm
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US,wilfordhancock com
1,S3-859268022,International South Consultants Private Ltd,NaN,India,international south consultants private ltd
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US,llc moncada léarning center
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US,moyna s coffee
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India,pvt efs print ventures ltd

In [49]:
def make_block_key(row):
    name = row["name_norm"]
    country = str(row["country"]).casefold().strip()
    
    return country + "_" + name[:4]

In [50]:
train1["block_key"] = train1.apply(make_block_key, axis=1)
train3["block_key"] = train3.apply(make_block_key, axis=1)

In [53]:
s3_blocks = {}

for idx, row in train3.iterrows():
    key = row["block_key"]
    s3_blocks.setdefault(key, []).append(row["entity_id"])

In [56]:
candidate_pairs = []

for _, row in train1.iterrows():
    s1_id = row["entity_id"]
    key = row["block_key"]
    
    
    for candidate_id in s3_blocks.get(key, []):
        candidate_pairs.append(
            (s1_id, candidate_id)
        )

MemoryError:

In [57]:
candidate_df = pd.DataFrame(
    candidate_pairs,
    columns=["source1_entity_id", "candidate_entity_id"]
)

print(candidate_df.head())
print("Candidate pairs:", len(candidate_df))

MemoryError:

In [54]:
print("S1:", len(train1))
print("S2:", len(train2))
print("S3:", len(train3))
print("Candidate pairs:", len(candidate_df))
print(candidate_df.head(10))

S1: 5285603
S2: 2206821
S3: 5034616

NameError: name 'candidate_df' is not defined

In [38]:
new_train1 = train1.iloc[:1000,:]
new_train3 = train3.iloc[:1000,:]
new_train2 = train2.iloc[:1000,:]
new_gr_truth = train_gr.iloc[:1000,:]

In [39]:
new_train1.shape,new_train3.shape

((1000, 4), (1000, 4))

In [44]:
new_train1.head(10)

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India
5,S3-578159284,LLC Hernandez Colonial Redwood,"2260- Housecreek Trail, Unit 407, Raleigh, Nor...",US
6,S3-121412624,Classic Equity Partners Group,"6885 Catalpa Bluff Ln, PO Box 5799, Dickinson,...",US
7,S3-249416830,Ectolumdrex dba X+ Madison Inc,"S03575 Cty Tk M, Town Of Buffalo, WI",US
8,S3-107644605,Animal Hanisch Hospirlg,"##8 Willow Oak Lane, Fl. 0, Saint Louis, Missouri",US
9,S3-160217003,Gomez Optimal,"343 Hempstead 161, Hope, Arkansas",US

In [41]:
new_train1[["business_address"]].head()

                                    business_address
0                        Mack Rd, Haltom City, Texas
1                                                NaN
2                    5780 Fawn Ct, Fort Worth, Texas
3       1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio
4  Door No 183, 41St Cross, 22Nd Main 9Th Block J...

In [46]:
split_b_address = new_train1["business_address"].str.split(",", expand=True)

In [47]:
split_b_address

,0,1,2,3,4,5,6,7,8,9,10
0,Mack Rd,Haltom City,Texas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5780 Fawn Ct,Fort Worth,Texas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1 Ivanhoe Ave,PO Box 6009,Cincinnati,Ohio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Door No 183,41St Cross,22Nd Main 9Th Block Jayanagar,Bengaluru Urban,Bangalore,ಕರ್ನಾಟಕ,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
995,2626 Creek Arbor Cir,Houston,Texas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,Apex,North Carolina,1011 Davis Drive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,13082 33,Gustine,California,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,15/C/1/B,Raja Santosh Roy Road,Kolkata,Kolkata,Howrah,West Bengal,NaN,NaN,NaN,NaN,NaN
999,B - 1-34,Shanti Sadan Co-op Hsg.,2Nd Floor 12A,Unnat Nagar,Goregoan - West,Mumbai,Mumbai City,महाराष्ट्र,NaN,NaN,NaN

In [37]:
new_train1.head(10)

,entity_id,business_name,business_address,country,address
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US,"[Mack Rd, Haltom City, Texas]"
1,S3-859268022,International South Consultants Private Ltd,NaN,India,NaN
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US,"[5780 Fawn Ct, Fort Worth, Texas]"
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US,"[1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio]"
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India,"[Door No 183, 41St Cross, 22Nd Main 9Th Bloc..."
5,S3-578159284,LLC Hernandez Colonial Redwood,"2260- Housecreek Trail, Unit 407, Raleigh, Nor...",US,"[2260- Housecreek Trail, Unit 407, Raleigh, ..."
6,S3-121412624,Classic Equity Partners Group,"6885 Catalpa Bluff Ln, PO Box 5799, Dickinson,...",US,"[6885 Catalpa Bluff Ln, PO Box 5799, Dickins..."
7,S3-249416830,Ectolumdrex dba X+ Madison Inc,"S03575 Cty Tk M, Town Of Buffalo, WI",US,"[S03575 Cty Tk M, Town Of Buffalo, WI]"
8,S3-107644605,Animal Hanisch Hospirlg,"##8 Willow Oak Lane, Fl. 0, Saint Louis, Missouri",US,"[##8 Willow Oak Lane, Fl. 0, Saint Louis, M..."
9,S3-160217003,Gomez Optimal,"343 Hempstead 161, Hope, Arkansas",US,"[343 Hempstead 161, Hope, Arkansas]"

In [24]:
new_train3.head(10)

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US
5,S2-138046867,Lee and Lawson,"1702 Pine Avenue, CITY OF MENOMONIE, WI",US
6,S2-584977605,SHIVSHAKTI VIDYALAYA VIDYALAYA OVERSEAS CORPOR...,"H.NO 204 C ROAD HOSHIARPUR, PUNJAB, Punjab",India
7,S2-277444929,Shree Infracon Private Ltd,"63/2275/7, ALHIND TOWER, FIRST FLOOR, JAFFERKH...",India
8,S2-721031885,Chavira Platinum Chimera LLC,"282 SAXONY DRIVE, FTT MITCHELL, KY",US
9,S2-508602797,FOUNDATION EXCEL AGENCY PRIVATE LIMITED,"HN 753 E-1, BHARAT NAGAR, 104/1/1 ERANDWANE, M...",India

In [28]:
new_train2.head(10)

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
5       S1-18727616  S2-755677256,S3-187831601,S3-641489370,S3-4762...
6      S1-318373630                          S2-660036492,S3-804600254
7       S1-86989137                          S3-274817120,S3-312496301
8       S1-29845983                          S2-648035184,S3-588502663
9      S1-789009573              S2-383871912,S3-74481402,S3-576451439

In [26]:
new_gr_truth.head(10)

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
5       S1-18727616  S2-755677256,S3-187831601,S3-641489370,S3-4762...
6      S1-318373630                          S2-660036492,S3-804600254
7       S1-86989137                          S3-274817120,S3-312496301
8       S1-29845983                          S2-648035184,S3-588502663
9      S1-789009573              S2-383871912,S3-74481402,S3-576451439

In [48]:
test1.head()

,entity_id,business_name,business_address,country
0,S1-714132312,Zephay Labs Inc,"2621 Cotten Road, Tyler, TX",US
1,S1-106407869,Vision Partners Corp,"IA, Iowa City, 1064 Newton Rd, Unit 11",US
2,S1-156285671,<< Team Ecole,"175 Boulevard du Président Franklin Roosevelt,...",France
3,S1-689823050,Red Perfect Trading,"Mirzapur, Ews 12, Uttar Pradesh, Mirzapursadar...",India
4,S1-921369899,ZNB Club SARL,"Nouvelle-Aquitaine, La Teste-de-Buch, 5 bis Ru...",France

In [49]:
test2.head()

,entity_id,business_name,business_address,country
0,S2-192345572,Brahma Infosoft,"COIMATORE COLONY, HUNSUR TQMYSORE DIST., Karna...",India
1,S2-566025912,Marina Ecole France Sarl,"63 R. DE DIEPPE, LILLE, Hauts-de-France",France
2,S2-158121477,SCI Ptit Àmicale,"18 RUE JEN ZAY, Dunkerque, Nord",France
3,S2-89663826,Apex Summit,"67 KENTUCKY ST, SALYERSVILLE, KY",US
4,S2-884102769,Fresh Truist,"8264 FILLY COURT, ROANOKE COUNTY, VA",US